name: t_store_admin_panel
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  clipboard: ^0.1.3
  cloud_firestore: ^5.6.5
  collection: ^1.19.1
  connectivity_plus: ^6.1.3
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  data_table_2: ^2.5.18
  dio: ^5.8.0+1
  dartz: ^0.10.1
  equatable: ^2.0.7
  file_picker: ^9.1.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dropzone: ^4.1.0
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.2
  get: ^4.7.2
  get_it: ^8.0.3
  iconsax: ^0.0.8
  intl: ^0.20.2
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  universal_html: ^2.2.4
  url_strategy: ^0.3.0
  flutter_typeahead: ^5.2.0
  multi_select_flutter: ^4.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1 
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #---------------------LOCAL ASSETS---------------------
  assets:
    - assets/logos/
    - assets/icons/payment_methods/
    - assets/images/content/
    - assets/images/products/
    - assets/images/animations/
    - .env
  #---------------------LOCAL FONTS---------------------
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
          
  #---------------------LAUNCH ICONS---------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logos/logo.png"
  windows:
    generate: true
    image_path: "assets/logos/logo.png"
    icon_size: 128
  macos:
    generate: true
    image_path: "assets/logos/logo.png"
