// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvFGa3n5L54ackJ_ceIrcziie9LRloBvE',
    appId: '1:1053148190415:web:67d6edffba8ffc4c8cc9ba',
    messagingSenderId: '1053148190415',
    projectId: 'ecommerceapp-a2faf',
    authDomain: 'ecommerceapp-a2faf.firebaseapp.com',
    storageBucket: 'ecommerceapp-a2faf.firebasestorage.app',
    measurementId: 'G-Y9KYF75B4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Qq_maKuVmEU8yP4T3ZkMN6Yc2ICKKlM',
    appId: '1:1053148190415:android:1cbffdb13e6379938cc9ba',
    messagingSenderId: '1053148190415',
    projectId: 'ecommerceapp-a2faf',
    storageBucket: 'ecommerceapp-a2faf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpkCIi4zUhvGgKAQ34C8IYMYdushvtKo',
    appId: '1:1053148190415:ios:40425ccbd58e0d2b8cc9ba',
    messagingSenderId: '1053148190415',
    projectId: 'ecommerceapp-a2faf',
    storageBucket: 'ecommerceapp-a2faf.firebasestorage.app',
    androidClientId: '1053148190415-0rfsbsmrq00n9us82ro1i44o0u5alsq7.apps.googleusercontent.com',
    iosClientId: '1053148190415-4m9nrn3oot22hfp7asat5907la5726h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStoreAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpkCIi4zUhvGgKAQ34C8IYMYdushvtKo',
    appId: '1:1053148190415:ios:40425ccbd58e0d2b8cc9ba',
    messagingSenderId: '1053148190415',
    projectId: 'ecommerceapp-a2faf',
    storageBucket: 'ecommerceapp-a2faf.firebasestorage.app',
    androidClientId: '1053148190415-0rfsbsmrq00n9us82ro1i44o0u5alsq7.apps.googleusercontent.com',
    iosClientId: '1053148190415-4m9nrn3oot22hfp7asat5907la5726h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStoreAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdbsNTtjG4W0TTpYe9wlql5ZXN4czNfKU',
    appId: '1:1053148190415:web:b1a5e4df47b7b4dc8cc9ba',
    messagingSenderId: '1053148190415',
    projectId: 'ecommerceapp-a2faf',
    authDomain: 'ecommerceapp-a2faf.firebaseapp.com',
    storageBucket: 'ecommerceapp-a2faf.firebasestorage.app',
    measurementId: 'G-396760GZ9M',
  );
}
